version: "2"

services:
  app:
    build: .
    ports:
     - "4000:4000"
    links:
     - db
    environment:
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
      - DATABASE_URL=postgresql://postgres@db/spectre
      - DOMAIN_NAME=app
      - PORT=:4000
      - PROTOCOL=http://
    volumes:
     - .:/app
    command: bash -c "rm -f /app/tmp/pids/*.pid && rake assets:precompile && SECRET_KEY_BASE=`rake secret` rails server -p 4000"

  db:
    image: postgres:9.6
    ports:
     - "5432"
    volumes:
     - .:/app
     - .:/public
     - data-db:/var/lib/postgresql/data
    environment:
     - POSTGRES_DB=spectre

volumes:
  data-db: {}
