development:
  adapter: postgresql
  encoding: utf8
  database: spectre_development
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: wafi-spectre
  pool: 5
  username: deploy
  port: 5432

test: &test
  adapter: postgresql
  encoding: utf8
  database: spectre_test
  pool: 5
  username:
  password:

cucumber:
  <<: *test
